# Generated by Django 6.0.3 on 2026-03-16 21:38

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('epub_file', models.FileField(blank=True, upload_to=books.models.book_directory_path)),
                ('cover_image', models.ImageField(blank=True, upload_to=books.models.book_directory_path)),
                ('asin', models.CharField(blank=True, default='', max_length=20)),
                ('isbn', models.CharField(blank=True, default='', max_length=20)),
                ('isbn13', models.CharField(blank=True, default='', max_length=20)),
                ('pages', models.IntegerField(blank=True, default=0)),
                ('publication_time', models.DateTimeField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('currently_reading', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('epub', 'Epub'), ('wishlist', 'Wishlist')], default='epub', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ManyToManyField(to='books.author')),
            ],
        ),
    ]
