CREATE TABLE media (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  size INTEGER NOT NULL,
  path TEXT NOT NULL UNIQUE,
  extension TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)
