services:
  backend:
    container_name: shiori-backend
    image: rust:1.94-alpine
    restart: unless-stopped
    working_dir: /backend
    ports:
      - "3000:3000"
    # environment:
    #   DATABASE_URL: mysql://shiori:shiori@db:3306/shiori
    volumes:
      - ./backend:/backend
      - ./dev/books:/books
      - ./dev/data:/data
    command: >
      sh -c "cargo install cargo-watch && cargo watch -x run"

  frontend:
    container_name: shiori-frontend
    image: oven/bun:1-alpine
    restart: unless-stopped
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
    command: sh -c "bun install && bun run dev"
