/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all libraries. */
        get: operations["list_libraries"];
        put?: never;
        /** Create a new library. */
        post: operations["create_library"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch library.
         * @description Not implemented
         */
        get: operations["get_library"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List library media. */
        get: operations["list_library_media"];
        put?: never;
        /** Upload a new media item to the specified library. */
        post: operations["create_library_media"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch media item. */
        get: operations["get_media"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update media information. */
        patch: operations["patch_media"];
        trace?: never;
    };
    "/api/v1/media/{id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch media cover. */
        get: operations["get_media_cover"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search for metadata. */
        get: operations["search_metadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Media: {
            /**
             * @description Endpoint where the cover is stored.
             * @example /api/v1/media/4/cover
             */
            cover_path?: string | null;
            /**
             * Format: date-time
             * @description Timestamp of when the media was created.
             * @example 2026-03-23T12:00:00Z
             */
            created_at: string;
            /**
             * @description File extension of the media.
             * @example epub
             */
            extension: string;
            /**
             * Format: int32
             * @description Unique identifier for the media item.
             * @example 86
             */
            id: number;
            /**
             * Format: int32
             * @description Library this media belongs to.
             * @example 2
             */
            library_id: number;
            /**
             * @description Name of the media file, excluding extension.
             * @example 86_Volume_1
             */
            name: string;
            /**
             * @description File system path where the media is stored.
             * @example /data/books/light_novels/86_Volume_1.epub
             */
            path: string;
            /**
             * Format: int64
             * @description Size of the media file in bytes.
             * @example 102400
             */
            size: number;
        };
        MediaMetadata: {
            /**
             * @description List of authors associated with the media item.
             * @example [
             *       "Asato Asato"
             *     ]
             */
            authors: string[];
            /**
             * @description Description of the media item.
             * @example The San Magnolia Republic...
             */
            description?: string | null;
            /**
             * @description List of genres associated with the media item.
             * @example [
             *       "Light Novel",
             *       "War"
             *     ]
             */
            genres: string[];
            /**
             * @description International Standard Book Number (ISBN).
             *     Typically used for books.
             * @example 1975303121
             */
            isbn?: string | null;
            /**
             * @description Language of the media content.
             * @example English
             */
            language?: string | null;
            /**
             * Format: date
             * @description Date the media was published.
             * @example 2019-03-26
             */
            published_at?: string | null;
            /**
             * @description Name of the publisher or publishing organization.
             * @example Yen On
             */
            publisher?: string | null;
        };
        PatchMetadata: {
            /** @description List of authors associated with the media item. */
            authors?: string[] | null;
            /**
             * @description Description of the media item.
             * @example The San Magnolia Republic...
             */
            description?: string | null;
            /**
             * @description List of genres associated with the media item.
             * @example [
             *       "Light Novel",
             *       "War"
             *     ]
             */
            genres?: string[] | null;
            /**
             * @description International Standard Book Number (ISBN).
             *     Typically used for books.
             * @example 1975303121
             */
            isbn?: string | null;
            /**
             * @description Language of the media content.
             * @example English
             */
            language?: string | null;
            /**
             * Format: date
             * @description Date the media was published.
             * @example 2019-03-26
             */
            published_at?: string | null;
            /**
             * @description Name of the publisher or publishing organization.
             * @example Yen On
             */
            publisher?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_libraries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully fetched libraries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: date-time
                         * @description Timestamp of when the media was created.
                         * @example 2024-11-08T17:23:41Z
                         */
                        created_at: string;
                        /**
                         * Format: int32
                         * @description Unique identifier for the library.
                         * @example 86
                         */
                        id: number;
                        /**
                         * @description Name of the library.
                         * @example Light Novels
                         */
                        name: string;
                        /**
                         * @description File system path to the library's directory.
                         * @example /data/books/light_novels
                         */
                        path: string;
                    }[];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_library: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Name of the library. */
                    name: string;
                    /** @description File system path to the library's directory. */
                    path: string;
                };
            };
        };
        responses: {
            /** @description Successfully created library */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: date-time
                         * @description Timestamp of when the media was created.
                         * @example 2024-11-08T17:23:41Z
                         */
                        created_at: string;
                        /**
                         * Format: int32
                         * @description Unique identifier for the library.
                         * @example 86
                         */
                        id: number;
                        /**
                         * @description Name of the library.
                         * @example Light Novels
                         */
                        name: string;
                        /**
                         * @description File system path to the library's directory.
                         * @example /data/books/light_novels
                         */
                        path: string;
                    };
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_library: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the library */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully fetched library */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Library not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_library_media: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the library */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully fetched library media */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Endpoint where the cover is stored.
                         * @example /api/v1/media/4/cover
                         */
                        cover_path?: string | null;
                        /**
                         * Format: date-time
                         * @description Timestamp of when the media was created.
                         * @example 2026-03-23T12:00:00Z
                         */
                        created_at: string;
                        /**
                         * @description File extension of the media.
                         * @example epub
                         */
                        extension: string;
                        /**
                         * Format: int32
                         * @description Unique identifier for the media item.
                         * @example 86
                         */
                        id: number;
                        /**
                         * Format: int32
                         * @description Library this media belongs to.
                         * @example 2
                         */
                        library_id: number;
                        /**
                         * @description Name of the media file, excluding extension.
                         * @example 86_Volume_1
                         */
                        name: string;
                        /**
                         * @description File system path where the media is stored.
                         * @example /data/books/light_novels/86_Volume_1.epub
                         */
                        path: string;
                        /**
                         * Format: int64
                         * @description Size of the media file in bytes.
                         * @example 102400
                         */
                        size: number;
                    }[];
                };
            };
            /** @description Library not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_library_media: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the library */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description An array of files to upload. */
                    files: number[];
                };
            };
        };
        responses: {
            /** @description Successfully added media to the library */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Endpoint where the cover is stored.
                         * @example /api/v1/media/4/cover
                         */
                        cover_path?: string | null;
                        /**
                         * Format: date-time
                         * @description Timestamp of when the media was created.
                         * @example 2026-03-23T12:00:00Z
                         */
                        created_at: string;
                        /**
                         * @description File extension of the media.
                         * @example epub
                         */
                        extension: string;
                        /**
                         * Format: int32
                         * @description Unique identifier for the media item.
                         * @example 86
                         */
                        id: number;
                        /**
                         * Format: int32
                         * @description Library this media belongs to.
                         * @example 2
                         */
                        library_id: number;
                        /**
                         * @description Name of the media file, excluding extension.
                         * @example 86_Volume_1
                         */
                        name: string;
                        /**
                         * @description File system path where the media is stored.
                         * @example /data/books/light_novels/86_Volume_1.epub
                         */
                        path: string;
                        /**
                         * Format: int64
                         * @description Size of the media file in bytes.
                         * @example 102400
                         */
                        size: number;
                    }[];
                };
            };
            /** @description Invalid uploaded media */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Library not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_media: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the media item */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully fetched media cover */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"] & {
                        metadata?: null | components["schemas"]["MediaMetadata"];
                    };
                };
            };
            /** @description Media not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_media: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the media item */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description URL of the cover image associated with the media.
                     * @example https://example.com/cover.jpg
                     */
                    cover_url?: string | null;
                    metadata?: null | components["schemas"]["PatchMetadata"];
                    /**
                     * @description Name of the media item.
                     * @example 86—EIGHTY-SIX, Vol. 1
                     */
                    name?: string | null;
                };
            };
        };
        responses: {
            /** @description Successfully updated media information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"] & {
                        metadata?: null | components["schemas"]["MediaMetadata"];
                    };
                };
            };
            /** @description Media not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_media_cover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the media item */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully fetched media cover */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Media or cover not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_metadata: {
        parameters: {
            query: {
                /** @description A search query string. */
                q: string;
                /**
                 * @description The provider to use for the search.
                 *     Defaults to "goodreads" if not provided in the query.
                 */
                provider?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully found metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description List of authors associated with the media item.
                         * @example [
                         *       "Asato Asato"
                         *     ]
                         */
                        authors: string[];
                        /**
                         * @description URL of the cover image associated with the media.
                         * @example https://example.com/cover.jpg
                         */
                        cover_url?: string | null;
                        /**
                         * @description Description of the media item.
                         * @example The San Magnolia Republic...
                         */
                        description?: string | null;
                        /**
                         * @description List of genres associated with the media item.
                         * @example [
                         *       "Light Novel",
                         *       "War"
                         *     ]
                         */
                        genres: string[];
                        /**
                         * @description International Standard Book Number (ISBN).
                         *     Typically used for books.
                         * @example 1975303121
                         */
                        isbn?: string | null;
                        /**
                         * @description Language of the media content.
                         * @example English
                         */
                        language?: string | null;
                        /**
                         * Format: date
                         * @description Date the media was published.
                         * @example 2019-03-26
                         */
                        published_at?: string | null;
                        /**
                         * @description Name of the publisher or publishing organization.
                         * @example Yen On
                         */
                        publisher?: string | null;
                        /**
                         * @description Title of the media item.
                         * @example 86—EIGHTY-SIX, Vol. 1
                         */
                        title: string;
                    };
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
