/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all libraries. */
        get: operations["list_libraries"];
        put?: never;
        /** Create a new library. */
        post: operations["create_library"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch library by id. */
        get: operations["get_library"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List library media. */
        get: operations["list_library_media"];
        put?: never;
        /** Upload a new media item to the specified library. */
        post: operations["create_library_media"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search for metadata. */
        get: operations["search_metadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NewLibraryRequest: {
            /** @description Name of the library. */
            name: string;
            /** @description File system path to the library's directory. */
            path: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_libraries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully fetched libraries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: date-time
                         * @description Timestamp of when the media was created.
                         * @example 2024-11-08T17:23:41Z
                         */
                        created_at: string;
                        /**
                         * Format: int32
                         * @description Unique identifier for the library.
                         * @example 86
                         */
                        id: number;
                        /**
                         * @description Name of the library.
                         * @example Light Novels
                         */
                        name: string;
                        /**
                         * @description File system path to the library's directory.
                         * @example /data/books/light_novels
                         */
                        path: string;
                    }[];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_library: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewLibraryRequest"];
            };
        };
        responses: {
            /** @description Successfully created library */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: date-time
                         * @description Timestamp of when the media was created.
                         * @example 2024-11-08T17:23:41Z
                         */
                        created_at: string;
                        /**
                         * Format: int32
                         * @description Unique identifier for the library.
                         * @example 86
                         */
                        id: number;
                        /**
                         * @description Name of the library.
                         * @example Light Novels
                         */
                        name: string;
                        /**
                         * @description File system path to the library's directory.
                         * @example /data/books/light_novels
                         */
                        path: string;
                    };
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_library: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the library */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully fetched library */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Library not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_library_media: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the library */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully fetched library media */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: date-time
                         * @description Timestamp of when the media was created.
                         * @example 2026-03-23T12:00:00Z
                         */
                        created_at: string;
                        /**
                         * @description File extension of the media.
                         * @example epub
                         */
                        extension: string;
                        /**
                         * Format: int32
                         * @description Unique identifier for the media item.
                         * @example 86
                         */
                        id: number;
                        /**
                         * @description Name of the library this media belongs to.
                         * @example Light Novels
                         */
                        library_id: string;
                        /**
                         * @description Name of the media file, excluding extension.
                         * @example 86_Volume_1
                         */
                        name: string;
                        /**
                         * @description File system path where the media is stored.
                         * @example /data/books/light_novels/86_Volume_1.epub
                         */
                        path: string;
                        /**
                         * Format: int64
                         * @description Size of the media file in bytes.
                         * @example 102400
                         */
                        size: number;
                    };
                };
            };
            /** @description Library not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_library_media: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the library */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully added media to the library */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Library not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_metadata: {
        parameters: {
            query: {
                /** @description A search query string. */
                q: string;
                /**
                 * @description The provider to use for the search.
                 *     Defaults to "goodreads" if not provided in the query.
                 */
                provider?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully found metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description List of authors associated with the media item.
                         * @example [
                         *       "Asato Asato"
                         *     ]
                         */
                        authors: string[];
                        /**
                         * @description International Standard Book Number (ISBN).
                         *     Typically used for books.
                         * @example 1975303121
                         */
                        isbn?: string | null;
                        /**
                         * @description Language of the media content.
                         * @example English
                         */
                        language?: string | null;
                        /**
                         * Format: date
                         * @description Date the media was published.
                         * @example 2019-03-26
                         */
                        published_at?: string | null;
                        /**
                         * @description Name of the publisher or publishing organization.
                         * @example Yen On
                         */
                        publisher?: string | null;
                    };
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
