// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `libraries` table.
    ///
    /// (Automatically generated by Diesel.)
    libraries (id) {
        /// The `id` column of the `libraries` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `name` column of the `libraries` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `path` column of the `libraries` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        path -> Text,
        /// The `created_at` column of the `libraries` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `media` table.
    ///
    /// (Automatically generated by Diesel.)
    media (id) {
        /// The `id` column of the `media` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `name` column of the `media` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `size` column of the `media` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        size -> Int8,
        /// The `path` column of the `media` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        path -> Text,
        /// The `extension` column of the `media` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        extension -> Text,
        /// The `created_at` column of the `media` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `library_id` column of the `media` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        library_id -> Int4,
        /// The `cover_path` column of the `media` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        cover_path -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `media_metadata` table.
    ///
    /// (Automatically generated by Diesel.)
    media_metadata (media_id) {
        /// The `media_id` column of the `media_metadata` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        media_id -> Int4,
        /// The `authors` column of the `media_metadata` table.
        ///
        /// Its SQL type is `Array<Nullable<Text>>`.
        ///
        /// (Automatically generated by Diesel.)
        authors -> Array<Text>,
        /// The `publisher` column of the `media_metadata` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        publisher -> Nullable<Text>,
        /// The `isbn` column of the `media_metadata` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        isbn -> Nullable<Text>,
        /// The `language` column of the `media_metadata` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        language -> Nullable<Text>,
        /// The `published_at` column of the `media_metadata` table.
        ///
        /// Its SQL type is `Nullable<Date>`.
        ///
        /// (Automatically generated by Diesel.)
        published_at -> Nullable<Date>,
    }
}

diesel::joinable!(media -> libraries (library_id));
diesel::joinable!(media_metadata -> media (media_id));

diesel::allow_tables_to_appear_in_same_query!(libraries, media, media_metadata,);
