# Generated by Django 6.0.3 on 2026-03-16 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalBookID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('goodreads', 'Goodreads')], max_length=20)),
                ('external_id', models.CharField(max_length=200)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='books.book')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'external_id'], name='metadata_ex_source_9357d6_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_external_book_source_id')],
            },
        ),
    ]
